name = "Zen of Python"
published = 2004-11-19T09:00:00-05:00
category = [ "Python" ]
summary = "Long time Pythoneer Tim Peters succinctly channels the BDFL's guiding principles for Python's design into 20 aphorisms, only 19 of which have been written down."
